filter:
    excluded_paths:
        - tests/*
build:
    tests:
        override:
            -
                command: 'vendor/bin/phpunit  --configuration tests/phpunit.xml --coverage-clover=some-file tests/'
                coverage:
                    file: 'some-file'
                    format: 'clover'