filter:
    excluded_paths:
        - tests/*

tools:
    external_code_coverage:
        timeout: 600
        runs: 3

build:
    tests:
        override:
            -
                command: 'vendor/bin/phpunit  --configuration tests/phpunit.xml --coverage-clover=some-file tests/'
                coverage:
                    file: 'some-file'
                    format: 'clover'